# Generated by Django 3.1.7 on 2021-12-11 18:26

from django.db import migrations, models
import django.db.models.deletion
from automations import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.get_group_model_setting()),
        ('automations', '0006_auto_20211121_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationtaskmodel',
            name='interaction_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.get_group_model_setting(), verbose_name='Assigned group'),
        ),
    ]

